<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-KRM7DIQ6" name="Test" tests="9" failures="5" timestamp="15 May 2022 07:42:28 GMT" time="9.438" errors="0">
  <testcase name="performOpeartion" time="0.628" classname="DDT.ExcelOperation">
    <failure type="java.lang.IllegalArgumentException" message="The workbook already contains a sheet of this name">
      <![CDATA[java.lang.IllegalArgumentException: The workbook already contains a sheet of this name
	at org.apache.poi.xssf.usermodel.XSSFWorkbook.createSheet(XSSFWorkbook.java:636)
	at org.apache.poi.xssf.usermodel.XSSFWorkbook.createSheet(XSSFWorkbook.java:67)
	at DDT.ExcelOperation.performOpeartion(ExcelOperation.java:23)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- performOpeartion -->
  <testcase name="ScreenShot1" time="8.756" classname="SampleTest.ScreenShot"/>
  <testcase name="test1" time="0.0" classname="RunRetryAnalyzer.Test1">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at RunRetryAnalyzer.Test1.test1(Test1.java:9)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- test1 -->
  <testcase name="test2" time="0.0" classname="RunRetryAnalyzer.Test1">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at RunRetryAnalyzer.Test1.test2(Test1.java:14)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
  <testcase name="test1" time="0.0" classname="Retryfailed.RetryTest">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase name="test1" time="0.008" classname="Retryfailed.RetryTest">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase name="test1" time="0.0" classname="Retryfailed.RetryTest">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase name="test1" time="0.0" classname="Retryfailed.RetryTest">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at Retryfailed.RetryTest.test1(RetryTest.java:9)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- test1 -->
  <testcase name="test2" time="0.0" classname="Retryfailed.RetryTest">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at Retryfailed.RetryTest.test2(RetryTest.java:13)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
</testsuite> <!-- Test -->
